name: Build
on:
  release:
    types:
    - created # on push does not work and `on: release` triggers 3 builds
jobs:
  release:
    name: release go binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@master
    - name: Version
      run: sed -i s/"master"/"${GITHUB_REF##*/}"/ cmd/cli.go
    - name: compile and release
      uses: wangyoucao577/go-release-action@v1.5
      env:
        CGO_ENABLED: "0" # support alpine
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
